### ISSUE TITLE
[About] Missing pictures

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#28]
In the "About" page we are missing the staff pictures.
In the mockup we initially had only a place for two, https://standardshub.atlassian.net/wiki/spaces/WEB/pages/30834834/About

but now we need to add  6 more (total 8). 
It is similar as before but we need two rows of 4 each. And we should be able to extend further rows of 4 image each.

See:  (as i didn't have the time to review the content, we went public with a different site temporarily www.standardshub.io)
![image](https://user-images.githubusercontent.com/3258579/92318244-2615a980-efbe-11ea-87ad-f12fe63abea4.png)

**Comment by jpradocueva** [comment]
In the assets / images I don't see a folder for "About". Where should I drop the above pictures of the staff?

**Comment by pattiyaa** [comment]
You can apply using "block_image_cards" template for this section to display image_cards style.
For the image folder of this page, that's right. You should keep in folder assets/images/about. 

Note: Each card's image needs to be config in about.markdown file, so even you have an image to about folder it will not display automatically without adding configuration.

I adjusted the about.markdown configuration for you to see, it's able to display layout as "www.standardshub.io". 
By the way, I download your colleague's photo from linkedin and it's color photo. If you want it to be black and white please feel fee to upload a new one.

**Comment by pattiyaa** [comment]
![screencapture-127-0-0-1-4000-about-2020-09-07-16_01_04](https://user-images.githubusercontent.com/23195322/92369595-67739980-f123-11ea-8869-b64bee516517.png)

**Comment by pattiyaa** [comment]
commited to dev branch

**Comment by jpradocueva** [comment]
thank you! I understand how to use different blocks in different pages. This is great!
