### ISSUE TITLE
[Home] Tagline text size

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#30]
In the home page:
![image](https://user-images.githubusercontent.com/3258579/92318492-dd5fef80-efc1-11ea-8ea3-d26753ad40a9.png)

The first line of the tagline "by standards professionals" needs to be increased it is too small compared with the second line
"For Standards Professionals"

Where the is stored the control of this text size?

**Comment by pattiyaa** [comment]
I've added these two configuration lines in index.markdown. 

- line1_font_size: "20px"
- line2_font_size: "40px"

**Comment by pattiyaa** [comment]
commited to dev branch

**Comment by jpradocueva** [comment]
thanks, it will make it easy to do some adjustments.
