### ISSUE TITLE
[Home] Add a button/link to "Block_text" question

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#31]
If I would like to add a button/link to the e.g. "Block_text" of the Home page.
Should just add the lines?:
* button_label: ''text"
* button_url: "URL"

![image](https://user-images.githubusercontent.com/3258579/92318736-822ffc00-efc5-11ea-8f62-feef7774512f.png)

**Comment by pattiyaa** [comment]
Yes, just add these lines if you want to show a button.  

- button_label: ''text"
- button_url: "URL"

It supports only button style, do you need a link style?  ( link style is the underlined text with blue color)

**Comment by jpradocueva** [comment]
If it is possible to also support link style then it will be great. This will give us full flexibility.
Is that possible?

**Comment by pattiyaa** [comment]
added 
button_style: "link" #display style as link | button(default)

for  
- block_image_cards
- block_image_text
- block_text_cards
- block_text_image

**Comment by jpradocueva** [comment]
In https://github.com/standardshub/sh-web/blob/v0_1/index.markdown

I have added a button ...

![image](https://user-images.githubusercontent.com/3258579/93422265-3fdda900-f868-11ea-8ffe-e684c9b522b9.png)

and it doesn't display it

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/3258579/93422435-a367d680-f868-11ea-8a4b-e89ec0bc64cf.png">

**Comment by jpradocueva** [comment]
Please ignore this problem. I believe that it was my branch that it was not correct.
