### ISSUE TITLE
[Footer] Social media configuration

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#35]
I see in the footer the social media icons.
![image](https://user-images.githubusercontent.com/3258579/92330000-81788380-f020-11ea-9960-eb9281028a40.png)

in the _Config.yml, I see
![image](https://user-images.githubusercontent.com/3258579/92330007-9523ea00-f020-11ea-864d-fb121a9471a4.png)

How do I configure:
* RSS and
* UTube

**Comment by pattiyaa** [comment]
Please follow this configulation below:
- rss_url: "/assets/feed.xml" #update the feed content in feed.xml file
- facebook_url: "https://www.facebook.com/{company}" #link to your facebook account
- twitter_url: "https://twitter.com/{company}" #link to your twitter account
- github_url: "https://github.com/{company}" #link to your github account
- linkedin_url: "https://www.linkedin.com/{company}" #link to your linkedin account
- youtube_url: "https://www.youtube.com/{company}" #link to your youtube account

Note: For any social account you don't want to display you can remove by add "#" in front of those lines.

**Comment by pattiyaa** [comment]
commited to dev branch

**Comment by jpradocueva** [comment]
Thank you!
