### ISSUE TITLE
[Footer] Copyright and version configuration

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#36]
How do I configure the copyright year and version described in the footer?

![image](https://user-images.githubusercontent.com/3258579/92330049-de743980-f020-11ea-8150-7984744ec37d.png)

**Comment by jpradocueva** [comment]
The file is _include / footer.html

**Comment by pattiyaa** [comment]
Fixed: by allow to add these configuration in _config.yml
- copy_right_year: "2020"
- version: "v1.0"

**Comment by pattiyaa** [comment]
commited to dev branch

**Comment by jpradocueva** [comment]
Thank you!! This makes things very easy for us!!
