### ISSUE TITLE
[Error] When running the demo server on the local machine

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#38]
This is the error that I am getting after running the following commands:
$ bundle install --path=vendor/bundle
$ bundle exec jekyll s

The website doesn't render in http://127.0.0.1:4000/

![image](https://user-images.githubusercontent.com/3258579/92331566-7a577280-f02c-11ea-8a0e-a3a13d01eee0.png)

**Comment by jpradocueva** [comment]
Problem resolved.
The issue is that inside of any "paragraph" attribute it doesn't allow a new paragraph.

I am looking for this (two paragraphs) under the same block
![image](https://user-images.githubusercontent.com/3258579/92332311-dcff3d00-f031-11ea-8590-4aacdc901400.png)

and I only can get ( a single paragraph)
![image](https://user-images.githubusercontent.com/3258579/92332343-2a7baa00-f032-11ea-9306-f9038f876933.png)

**Question**
Is possible to introduce a </br> between the pagraphs?

**Comment by pattiyaa** [comment]
To introduce a between paragraphs you can add `<br/>` tag where you want to add a new line.
and if you would lie to set text alignment to left you can add this new configuration to block_text template

From your reference style, the text seems to align on left and show almost full width, I suggest using block_text_fluid tempalte and add this new configuration to layout block

- paragraph_aligh: left

![image](https://user-images.githubusercontent.com/23195322/92382354-a828de00-f136-11ea-9607-79c9214338c4.png)

**Comment by pattiyaa** [comment]
commited to dev branch

**Comment by jpradocueva** [comment]
thank you!
