### ISSUE TITLE
[Font size] handling

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#41]
We need to manipulate the font-size of:

* paragraphs inside of text-block
* titles in some of the blocks

Where I can manipulate that size, directly in the CSS?
Is possible to apply different font-size on different blocks?

**Comment by pattiyaa** [comment]
For the font size, it's better to update for the whole site. So I recommended yo manipulate directly in CSS (assets/css/style.css)

- paragraph: change **font-size** in body{}
- title: change **h1, h2, h3**    

![image](https://user-images.githubusercontent.com/23195322/92386660-64d26d80-f13e-11ea-9b06-99ddd2a57fff.png)
![image](https://user-images.githubusercontent.com/23195322/92386799-b24eda80-f13e-11ea-89ff-0056de5aa3fa.png)

**Comment by jpradocueva** [comment]
thanks!
