### ISSUE TITLE
[block_icon_cards] click button

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#42]
Is possible to introduce a "See More | Learn More" button on these cards if needed?

![image](https://user-images.githubusercontent.com/3258579/92332642-48e2a500-f034-11ea-91a7-d99a9c6f53e3.png)

**Comment by pattiyaa** [comment]
Fixed
1. added  button to block_icon_cards 
2. apply more logic to show/hide button  (if config both button_lable and button_url will show button as button_style)
3. add align configuration to control alignment of card element

-    button_lable: "Lean More"
-    button_url: "xxx"
-    button_style: "link" #display style as link | button(default)
-    align: center # center | left | right

![image](https://user-images.githubusercontent.com/23195322/93021969-4d98f180-f610-11ea-9430-5e5597a5fc84.png)

**Comment by jpradocueva** [comment]
In this branch/and file https://github.com/standardshub/sh-web/edit/v0_1/index.markdown

I have added a button ...

![image](https://user-images.githubusercontent.com/3258579/93420858-c09aa600-f864-11ea-9133-acd45ff92c42.png)

but it doesn't display it.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/3258579/93420924-e58f1900-f864-11ea-9120-2dc9a0b6add7.png">

**Comment by jpradocueva** [comment]
Please ignore this problem. My branch was not up to date.
