### ISSUE TITLE
[block_text_cards] issue

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#43]
This block is great, it has a title (introduction) and then allows creating one or more columns.

The issue that I find is:
* that we need to create more rows of the text_cards but without the header (we have around 8 services and I would like to have at least two rows of 4 cards or even two rows of three cards and one with two cards.

* Icon, it will be good to have a little icon above the title to the right (see temporal website https://www.standardshub.io/)

If we have the possibility to leave blank the header part it will be great. Thre is nothing to do

Examples of icons in our temporal website.

![image](https://user-images.githubusercontent.com/3258579/92332906-c5c24e80-f035-11ea-9de3-92a96b6d8a60.png)

![image](https://user-images.githubusercontent.com/3258579/92332752-f786e580-f034-11ea-9c5c-6a4e37fc02f1.png)

**Comment by pattiyaa** [comment]
The header section is optional, you can remove it and it won't be displayed.

**Comment by pattiyaa** [comment]
fixed: by adding image and image_aligh to block_text_cards template

example card item
      - title: Formation
        paragraph: There are a number of ways to effectively start a new technical standards project. We will guide you to the path that best fits your needs.
        image: assets/images/home/section-icon.png
        image_align: right # left|center|right
        button_lable: "Lean More"
        button_url: ""

**Comment by pattiyaa** [comment]
committed code to dev branch

**Comment by jpradocueva** [comment]
fantastic!
