### ISSUE TITLE
[block_image_cards] button is not displayed

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#51]
In https://github.com/standardshub/sh-web/blob/v0.1/index.markdown line 97
"block_image_cards" the cards have been added a button but it doesn't display it.

![image](https://user-images.githubusercontent.com/3258579/92561173-8c056980-f228-11ea-8d9b-9bfe8c27c498.png)

![image](https://user-images.githubusercontent.com/3258579/92561241-b2c3a000-f228-11ea-8156-73c9c7eb1a3d.png)

**Comment by pattiyaa** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/23195322/93023634-7920d980-f61a-11ea-8bf8-a283a087673c.png)
