### ISSUE TITLE
Swap the position of SH Logos

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#6]
I suggest swapping the position of the SH-logos.

Please move the logo at the header (see below), to the footer
![image](https://user-images.githubusercontent.com/3258579/89723400-793e1180-d9aa-11ea-9c6e-1fba00f7554c.png)

and move the logo at the footer (see below)  to the header:
![image](https://user-images.githubusercontent.com/3258579/89723427-e3ef4d00-d9aa-11ea-9338-2d529eaafc67.png)

If there is a problem in the header, with the size of the tag-line, then we will need to find an alternative.

**Comment by pattiyaa** [comment]
noted

**Comment by jpradocueva** [comment]
I believe that these are the changes to swap the logos from header to footer and reverse:

**Header**
_includes/header.html 
<img src="/assets/images/logo.png" alt={{ site.title }} /> change this image for "logo_footer.png"

**Footer**
_includes/footer.html
<img class="logo_footer_img float-md-right" src="/assets/images/logo_footer.png" alt=""> change this image for the one above "logo.png"

but what to do when the top menu is compacted once the user starts scrolling down?

**Comment by jpradocueva** [comment]
I have applied the changes in the dev pages and it seems working ok

See http://devwww.standardshub.io/

**Comment by jpradocueva** [comment]
You are right, I didn't change the name of the logos. I just wanted to check how it looks like.
Shall I change it or will you or your team do it? 
I don't mind is just to be coordinated.

**Comment by pattiyaa** [comment]
I've update file logo.png and logo_footer.png to the image that you provide, and already rollback the template source code to call these two files.

**Comment by jpradocueva** [comment]
Thanks Patti!
